doc-warnings: no
test-warnings: no
strictness: medium
max-line-length: 120
uses:
    - django
autodetect: yes
ignore-paths:
    - ci
    - docs
    - etc
    - graphics
    - media
    - pki
python-targets:
    - 3
