[tool.black]
line-length = 120
target-version = ['py37', 'py38']
exclude = '''
(
  /(
    | env
    | venv
    | out
    | .+/migrations
  )/
)
'''



[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120


[tool.mypy]
python_version = "3.7"
exclude = "(env|venv|out|migrations)"

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

strict_equality = true

show_error_codes = true
pretty = true

warn_unused_configs = true
ignore_missing_imports = true
