psql:
  dbname: bounca
  username: bounca
  password: fsRWF2k2k
  host: postgres
  port: 5432

django:
  debug: True
  secret_key: 'pleasechangemeimsecret'
  hosts:
    - localhost
    - 127.0.0.1

mail:
  host: localhost
  # port: 587 optionally, only for tls and ssl
  # username: <user>
  # password: <password>
  # connection: none # allowed values: none, tls, ssl
  admin: jeroen@bounca.org
  from: no-reply@bounca.org

certificate-engine:
  key_algorithm: ed25519 # allowed values: ed25519, rsa

registration:
  email_verification: mandatory # allowed values: mandatory, optional, off
